#ifndef PUZZLEBOTS_SYSTEM_ENUMS_H
#define PUZZLEBOTS_SYSTEM_ENUMS_H

typedef enum SystemId {
    ACTION_SYSTEM,
    ACTIVATION_SYSTEM,
    ANIMATION_SYSTEM,
    BOT_SENSE_SYSTEM,
    BOT_AUTOMATON_SYSTEM,
    BOT_VISION_SYSTEM,
    BUTTON_SYSTEM,
    CAMERA_SYSTEM,  //5
    CONTAINER_SYSTEM,
    ENDLEVEL_SYSTEM,
    GRAVITY_SYSTEM,
    INPUT_SYSTEM,
    LED_SYSTEM,    //10
    MOVE_SYSTEM,
    EYEIMU_SYSTEM,
    RENDER_SYSTEM,  //15
    TELEPORT_SYSTEM,
    VISIBILITY_SYSTEM,

    SYSTEM_ID_SIZE
} SystemId;

#endif //PUZZLEBOTS_SYSTEM_ENUMS_H
